#!/bin/bash

src=$1
target=$2
LOG=/opt/rtorrent/log/moveLog.txt
baseDir=`basename ${target}`

echo "`date`: Moving - Source:${src} --> Target:${target}" >> $LOG
mv -u "${src}" "${target}"

if [ "${baseDir}" == "Movie_UnNamed" ]; then
	echo "";
elif [ "${baseDir}" == "unsortedMusic" ]; then
	echo "`date`: Music file found"
fi

echo " " >> $LOG
